
title: Uncollected Pages
description: tech. design. games. food. life. psycosis.
url: https://blog.alokprateek.ml/
permalink: ':title/'

baseurl: ""
markdown: kramdown
highlight: rouge

sass:
    style: compressed
  
#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

# Tracker
analytics: UA-85177250-1

# Comments
disqus-shortname: oxyenyos

# Contact form
# Go to https://getsimpleform.com and get a API token by signing up with your email and enter that here
api-token:   

include: [_pages]
version: 0.9
paginate: 6
paginate_path: "/page:num/"


# Output options (more information on Jekyll's site)
timezone: "Asia/Kolkata"

plugins: 
    - jekyll-paginate
    - jekyll-seo-tag
